### PR TITLE
Added new machines

### PR DESCRIPTION
**Pull request by jviskari**
Huyndai SUPER-16T
Huyndai SUPER-16TE
CBM PC10C

### CODE REVIEW

**Comment by michael-manley** [comment]
I will take a look at this and see if i can manually merge with dev. For future reference, the dev branch is main. I need to change the default branch from master to dev :)

**Comment by michael-manley** [comment]
@jviskari Do you have the roms for the following boards? I have the one for the Commodore and seems to work fine on sanity check.

Huyndai SUPER-16T
Huyndai SUPER-16TE

Please email them to mjmanley@ntge.net so I can run some sanity checks if you do. Please don't post them in chat.

**Comment by jviskari** [comment]
Hi @michael-manley, I'll send you email.

**Comment by michael-manley** [comment]
I merged this already, so I will close this :)

**Pull request closed without merging**
