### PR TITLE
Update compatibility list

### PR DESCRIPTION
**Pull request by unreal9010**
Added many entries of software that I tested under v17 (and which I legally own).

### CODE REVIEW

**Comment by sarah-walker-pcem** [comment]
I don't think updating TESTED.md in a development branch is particularly useful. I'd expect compatibility in such a branch to vary wildly over time. It would be useful for a release branch only, where major code changes are expected to stop after a certain point.

**Comment by unreal9010** [comment]
All my entries are valid for software tested under the last official PCem release v17 over the course of the past year. I don't think changes made after the last official release would break any compatibility with the software that I tested. Just to make sure, I once again tested some of the stuff from the list with the latest development build and I can confirm it still works.

**Comment by michael-manley** [comment]
@sarah-walker-pcem How did you use that document in past versions. Updated when someone motioned it was working in v<Insert Release Version Here>?

If he did test in v17 I think its safe to approve. I do agree that document should only be updated with compatibility tested on release builds.

**Comment by leilei-** [comment]
On past releases, in the weeks leading up to a release, there would be a feature-freeze, and that's when the running-everything-to-report-results phase starts and the list is made of the results in a forum thread.

**Comment by sarah-walker-pcem** [comment]
What @leilei- said. The compatibility list was only for pre-release sanity testing, and I never updated it once a release was out.

**Comment by michael-manley** [comment]
I think for now I will close it, and we can look into reopening it once I'm ready for a v18 release :)

**Pull request closed without merging**
