### PR TITLE
Mac support

### PR DESCRIPTION
**Pull request by MaddTheSane**
Initial Mac support.
Based on the work of @almeath  and @kode54 at https://github.com/PCemOnMac/PCemV17macOS

### CODE REVIEW

**Comment by sarah-walker-pcem** [comment]
Changes to SDL #include breaks the Windows build.

**Comment by Shambler2** [comment]
Have done some testing on the other project when they were attempting to add M1 support on macOS - one of the changes needed for that support doesn't appear to be in this pull request, configure.ac requires some minor changes to correctly identify the M1 as an arm CPU: 
`AC_MSG_CHECKING([for cpu])
case "${host_cpu}" in
    arm)
    CPU=arm64 # MacOS has "arm" in the host string
    AC_MSG_RESULT(${host_cpu})
    ;;
`

**Comment by MaddTheSane** [comment]
I know.
I don't want to use that override due to the fact that it might confuse checks on 32-bit ARM machines. 
The check will need to be more advanced than @almeath's way.
I got around this by passing `--build=aarch64-apple-darwin20.4.0` to configure. This isn't ideal, I know.

**Comment by Shambler2** [comment]
Yep figured that might have been the case :) 

Not ideal but thanks for the workaround for now

**Pull request merged**
